data_mode: historical

historical:
  days:    1
  hours:   0
  minutes: 0

algorithms:
  - PairTrading

active_strategies:
  - goog_amzn
  - aapl_msft

strategies:
  - name: aapl_msft
    symbol1: AAPL
    symbol2: MSFT
    window:   60
    entry_z:  2.5
    exit_z:   0.25
    risk_per_trade:      1

  - name: goog_amzn
    symbol1: GOOG
    symbol2: AMZN
    window:   60
    entry_z:  2.5
    exit_z:   0.5
    risk_per_trade:      1