ALTER TABLE user_configs
  ADD COLUMN IF NOT EXISTS trade_currency VARCHAR(3) NOT NULL DEFAULT 'EUR';

ALTER TABLE ai_positions
  ADD COLUMN IF NOT EXISTS trade_currency VARCHAR(3) NOT NULL DEFAULT 'EUR';
