ALTER TABLE user_configs
  ADD COLUMN IF NOT EXISTS soft_stop_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS soft_stop_hold_minutes INT NOT NULL DEFAULT 360,
  ADD COLUMN IF NOT EXISTS soft_stop_drawdown_pct NUMERIC(6, 4) NOT NULL DEFAULT 0.025;
